### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by arademaker** [cicerocaze/reve#2]
The readfile is empty. How to install the software? I tried to use `make' but the `Makefile` does not have a default target:

```
$ make
Makefile:803: *** multiple target patterns.  Stop.
```

Please add also the description about Perl dependencies. It also seems that the code dependents on the SQL Lite DB, is that right? Can you provide the script to create the DB scheme? 

Finally, I suggest create a Dockerfile  (https://www.docker.com) so people can easily install it with all its dependencies.

**Comment by cicerocaze** [comment]
Hi, Alexandre!

When I started collaborating with this app, I had the same problem. I tried to build using the Makefile, but no success. So, I started following log file and fixing the problems, downloading dependencies manually using cpan and trying...

I would create the readme, but the aplication never had any documentation and "Dancer2" framework is not mature and not very easy to understand, as they say. Probably, It wouldn't help too much. In fact, it would be hard to describe all the dependencies because, first: I did not create the project, second: there are many dependencies, I can not remember all, and third: I am very new with Perl. So, you can imagine how I suffered to get this up (googling too much).

However, I am going to try to create a readme about how to install it. It doesn't mean will work properly. How I said, Dancer2 is not mature. And the app has lots of issues. I already fixed lots of basic problems, but there are too many yet. 

Regards,

**Comment by arademaker** [comment]
It may be a good idea to open issues for each problem.

**Comment by cicerocaze** [comment]
Of course! By the way, thanks for helping!
